import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Web Dashboard Bereich
    {
      type: 'html',
      value: '<div class="sidebar-section-title">Web Dashboard</div>',
      className: 'sidebar-section-header',
    },
    {
      type: 'doc',
      id: 'home',
      label: 'Übersicht',
    },
    {
      type: 'category',
      label: 'Erste Schritte',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Einrichtung Ihres Orderlyze-Systems - Unternehmensdaten, Räume und Tische konfigurieren.',
      },
      items: [
        { type: 'autogenerated', dirName: 'erste-schritte' },
      ],
    },
    {
      type: 'category',
      label: 'Stammdaten',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Produkte, Kategorien, Extras und Gutscheine verwalten.',
      },
      items: [
        { type: 'autogenerated', dirName: 'stammdaten' },
      ],
    },
    {
      type: 'category',
      label: 'Personal & Kunden',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Benutzer und Stammkunden verwalten.',
      },
      items: [
        { type: 'autogenerated', dirName: 'personal' },
      ],
    },
    {
      type: 'category',
      label: 'Betrieb & Küche',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Küchenmonitor, Gänge und täglicher Betrieb.',
      },
      items: [
        { type: 'autogenerated', dirName: 'betrieb' },
      ],
    },
    {
      type: 'category',
      label: 'Auswertung & Berichte',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Berichte, Statistiken und Buchhaltungs-Export.',
      },
      items: [
        { type: 'autogenerated', dirName: 'auswertung' },
      ],
    },
    {
      type: 'category',
      label: 'Einstellungen',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Systemkonfiguration und erweiterte Optionen.',
      },
      items: [
        { type: 'autogenerated', dirName: 'einstellungen' },
      ],
    },

    // Trennlinie
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },

    // Mobile App Bereich
    {
      type: 'html',
      value: '<div class="sidebar-section-title">Mobile App</div>',
      className: 'sidebar-section-header',
    },
    {
      type: 'doc',
      id: 'app-home',
      label: 'App Übersicht',
    },
    {
      type: 'category',
      label: 'App Bereiche',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'app' },
      ],
    },

    // Trennlinie
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },

    // Hilfe Bereich
    {
      type: 'html',
      value: '<div class="sidebar-section-title">Hilfe</div>',
      className: 'sidebar-section-header',
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Häufig gestellte Fragen.',
      },
      items: [
        { type: 'autogenerated', dirName: 'faq' },
      ],
    },
    {
      type: 'category',
      label: 'Problemlösung',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Lösungen für häufige Probleme.',
      },
      items: [
        { type: 'autogenerated', dirName: 'troubleshooting' },
      ],
    },
  ],
};

export default sidebars;
