import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  troubleshootingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'troubleshooting',
    },
  ],
  faqSidebar: [
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
  ],
};

export default sidebars;
