import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Web Dashboard Bereich
    {
      type: 'category',
      label: 'Web Dashboard',
      collapsed: false,
      collapsible: true,
      className: 'sidebar-section-header',
      link: {
        type: 'doc',
        id: 'home',
      },
      items: [
        {
          type: 'category',
          label: 'Erste Schritte',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Einrichtung Ihres Orderlyze-Systems - Unternehmensdaten, Räume und Tische konfigurieren.',
          },
          items: [
            { type: 'autogenerated', dirName: 'erste-schritte' },
          ],
        },
        {
          type: 'category',
          label: 'Stammdaten',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Produkte, Kategorien, Extras und Gutscheine verwalten.',
          },
          items: [
            { type: 'autogenerated', dirName: 'stammdaten' },
          ],
        },
        {
          type: 'category',
          label: 'Personal & Kunden',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Benutzer und Stammkunden verwalten.',
          },
          items: [
            { type: 'autogenerated', dirName: 'personal' },
          ],
        },
        {
          type: 'category',
          label: 'Betrieb & Küche',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Küchenmonitor, Gänge und täglicher Betrieb.',
          },
          items: [
            { type: 'autogenerated', dirName: 'betrieb' },
          ],
        },
        {
          type: 'category',
          label: 'Auswertung & Berichte',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Berichte, Statistiken und Buchhaltungs-Export.',
          },
          items: [
            { type: 'autogenerated', dirName: 'auswertung' },
          ],
        },
        {
          type: 'category',
          label: 'Einstellungen',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Systemkonfiguration und erweiterte Optionen.',
          },
          items: [
            { type: 'autogenerated', dirName: 'einstellungen' },
          ],
        },
      ],
    },

    // Bonier App Bereich
    {
      type: 'category',
      label: 'Bonier App',
      collapsed: true,
      collapsible: true,
      className: 'sidebar-section-header',
      link: {
        type: 'doc',
        id: 'app/app-home',
      },
      items: [
        { type: 'autogenerated', dirName: 'app' },
      ],
    },

    // Hilfe Bereich
    {
      type: 'category',
      label: 'Hilfe',
      collapsed: true,
      collapsible: true,
      className: 'sidebar-section-header',
      items: [
        {
          type: 'category',
          label: 'FAQ',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Häufig gestellte Fragen zu Orderlyze.',
          },
          items: [
            { type: 'autogenerated', dirName: 'faq' },
          ],
        },
        {
          type: 'category',
          label: 'Problemlösung',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Lösungen für häufige Probleme.',
          },
          items: [
            { type: 'autogenerated', dirName: 'troubleshooting' },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
